// export const FETCH_BOARDS_REQUEST = 'FETCH_BOARDS_REQUEST';
// export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
// export const FETCH_BOARDS_FAILURE = 'FETCH_BOARDS_FAILURE';


export const SET_BOARD_DATA = 'SET_BOARD_DATA';
export const SET_BOARD_FETCH_ERROR = 'SET_BOARD_FETCH_ERROR';